#!/bin/sh
#
# Copyright 2016 Ciena Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#    http://www.apache.org/license/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, sofware
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
PID_FILE=/var/run/callhome.pid
SCRIPT=/etc/init.d/callhome.sh
SCRIPT_OPTS=
LOG_FILE=/var/log/callhome.log

#SCRIPT=/home/ubuntu/src/callhome/callhome.sh
#SCRIPT_OPTS="-i em2"

isrunning() {
	RUN=0
        if [ -f $PID_FILE ]; then
		DAEMON_PID=`cat $PID_FILE`
		IS_RUNNING=`ps $DAEMON_PID | grep -v PID`
		if [ "$IS_RUNNING X" != " X" ]; then
			RUN=1
		else
			rm -f $PID_FILE
		fi
	fi
	echo $RUN
}

start() {
	if [ `isrunning` -eq 1 ]; then
		echo "already running" >&2
		RETVAL=1
		return
	fi
	echo -n "Starting $prog:"
	bash -c "echo \$\$ > $PID_FILE && exec $SCRIPT $SCRIPT_OPTS 2>&1 > $LOG_FILE"&
	RETVAL=0
	echo
}

stop() {
        if [ `isrunning` -eq 0 ]; then
		if [ $# -eq 0 ]; then
			echo "not running" >&2
		fi
		RETVAL=1
		return
	fi
	echo -n "Stopping $prog:"
	kill -TERM `cat $PID_FILE`
	rm -f $PID_FILE
        RETVAL=0
	echo
}

reload() {
	echo -n "Reloading $prog:"
	if [ `isrunning` -eq 1 ]; then
		kill -TERM `cat $PID_FILE`
	fi
	start
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop -no-error
		start
		;;
	reload)
		stop -no-error
		start
		;;
	status)
		if [ -f $PID_FILE ]; then
			if [ `isrunning` -eq 0 ]; then
				echo "not running, but has PID file"
			else
				echo "running with PID "`cat $PID_FILE`
			fi
		else
			echo "not running"
		fi
		RETVAL=0
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
